django/task/account/urls.py
from django.urls import path
from .import views

app_name="account"

urlpatterns = [
    path('signup/', views.signup ,name='signup'),
    path('login/', views.loginform ,name='login'),
    path('logout/', views.logoutopp ,name='logout'),
    path('random/', views.randomizer, name='random')    
]

django/task/task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from account import views as account_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('',account_views.signup,name='home')

]

urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django/task/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from ratelimit.decorators import ratelimit
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required


# Create your views here.


def signup(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #create User
            user=form.save()
            login(request,user)
            return redirect('account:login')
    else:
        form = UserCreationForm()
    
    return render(request,'account/signup.html',{'form':form})



def loginform(request):

    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user= form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:

                return redirect('account:random')

    else:
        form= AuthenticationForm()
    return render(request,'account/login.html',{'form':form })

def logoutopp(request):
    if request.method=="POST":
        logout(request)
        return redirect('account:login')

@login_required (login_url='/account/login/')
@ratelimit(key='ip', rate='5/m', method=['GET', 'POST'])
def randomizer(request):
    was_limited = getattr(request, 'limited', False)
    if was_limited:
        raise PermissionDenied()
    else:
        return render(request,'account/random.html')

django/task/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>API</title>
    <link rel="stylesheet"  href="{% static 'styles.css'%}">
</head>
<body>

<div class="wrapper">
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form class="logout-link" action="{%url 'account:logout'%}" method="post">
                    {%csrf_token%}
                    <button type="submit" >Logout</button>

                </form>
            </li>
            {% else %}
            <li>
                <form class="login-link" action="{%url 'account:login'%}" method="post">
                    {%csrf_token%}
                    <button type="submit" >Login</button>

                </form>
            </li>
            <li>
                <form class="signup-link" action="{%url 'account:signup'%}" method="post">
                    {%csrf_token%}
                    <button type="submit" >Signup</button>

                </form>
            </li>
            {% endif %}
        </ul>
    </nav>
    {%block content%}
    
    {%endblock%}
</div>

</body>
</html>